apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backendmono
  name: backendmono
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: backendmono
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backendmono
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
          image: svenram/proyectoinfra:backendmono-1.0.6
          name: backend-mono
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /app/backend
              name: backendmono-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: backendmono-cm0
          name: backendmono-cm0
