apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: db-mono
  name: db-mono
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-mono
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: db-mono
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: lavadero
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:9.1.0
          name: db-mono
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
