apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontendmono
  name: frontendmono
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontendmono
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frontendmono
    spec:
      containers:
        - image: svenram/proyectoinfra:frontendmono-1.0.3
          name: frontend-mono
          ports:
            - containerPort: 4200
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
